// Track configuration — the heart of the multi-audience portal.
//
// Each track targets a different kind of user (working professional, 11+ student,
// English-prep student, English-prep professional). The same daily-word engine
// powers all of them; only the word list and the example format change.
//
// exampleFormat:
//   'workplace' -> tabs are Email / Chat / Speaking (generated from templates)
//   'exam'      -> tabs are In a Sentence / Synonyms / Antonyms
//
// Word schema: { word, partOfSpeech, meaning, synonyms[], antonyms[], sentence }
// Add more words to any track's `words` array to grow that track.

export const TRACKS = [
  {
    id: 'workplace',
    name: 'Workplace English',
    short: 'Workplace',
    audience: 'Professionals at work',
    tagline: 'Sound clear and confident in emails, meetings, and presentations.',
    icon: 'work',
    color: '#3A6E7E',
    comingSoon: true,
    exampleFormat: 'workplace',
    words: [
      {
        word: 'leverage',
        partOfSpeech: 'verb',
        meaning: 'to use something to maximum advantage.',
        synonyms: ['utilise', 'harness', 'capitalise on'],
        antonyms: ['waste', 'neglect'],
        sentence: 'We can leverage our existing customers to launch the new product.',
      },
      {
        word: 'streamline',
        partOfSpeech: 'verb',
        meaning: 'to make a process simpler and more efficient.',
        synonyms: ['simplify', 'optimise', 'rationalise'],
        antonyms: ['complicate', 'hinder'],
        sentence: 'The new software helped streamline the approval process.',
      },
      {
        word: 'consensus',
        partOfSpeech: 'noun',
        meaning: 'a general agreement reached by a group.',
        synonyms: ['agreement', 'accord', 'unanimity'],
        antonyms: ['disagreement', 'dissent'],
        sentence: 'After a long discussion, the team reached a consensus.',
      },
      {
        word: 'delegate',
        partOfSpeech: 'verb',
        meaning: 'to give a task or responsibility to another person.',
        synonyms: ['assign', 'entrust', 'hand over'],
        antonyms: ['retain', 'hoard'],
        sentence: 'A good manager knows how to delegate tasks effectively.',
      },
      {
        word: 'proactive',
        partOfSpeech: 'adjective',
        meaning: 'acting in advance to deal with an expected change or problem.',
        synonyms: ['anticipatory', 'prepared', 'forward-thinking'],
        antonyms: ['reactive', 'passive'],
        sentence: 'Being proactive about feedback prevents bigger problems later.',
      },
      {
        word: 'articulate',
        partOfSpeech: 'verb',
        meaning: 'to express an idea clearly and effectively.',
        synonyms: ['express', 'convey', 'communicate'],
        antonyms: ['mumble', 'obscure'],
        sentence: 'She was able to articulate her ideas clearly in the meeting.',
      },
      {
        word: 'pragmatic',
        partOfSpeech: 'adjective',
        meaning: 'dealing with things sensibly and realistically.',
        synonyms: ['practical', 'sensible', 'realistic'],
        antonyms: ['idealistic', 'impractical'],
        sentence: 'We took a pragmatic approach and fixed the most urgent issue first.',
      },
      {
        word: 'facilitate',
        partOfSpeech: 'verb',
        meaning: 'to make an action or process easier.',
        synonyms: ['ease', 'enable', 'assist'],
        antonyms: ['hinder', 'obstruct'],
        sentence: 'The new tool will facilitate collaboration across teams.',
      },
    ],
  },
  {
    id: 'eleven-plus',
    name: '11+ Exam',
    short: '11+',
    audience: 'Children preparing for the 11+',
    tagline: 'Exam-grade words with synonyms, antonyms, and easy example sentences.',
    icon: 'school',
    color: '#2E6B4F',
    primary: true,
    exampleFormat: 'exam',
    words: [
      {
        word: 'abundant',
        partOfSpeech: 'adjective',
        meaning: 'existing in large quantities; plentiful.',
        synonyms: ['plentiful', 'ample', 'copious'],
        antonyms: ['scarce', 'sparse'],
        sentence: 'The orchard was abundant with ripe, juicy apples.',
      },
      {
        word: 'benevolent',
        partOfSpeech: 'adjective',
        meaning: 'kind, generous, and caring towards others.',
        synonyms: ['kind', 'generous', 'caring'],
        antonyms: ['cruel', 'mean'],
        sentence: 'The benevolent stranger paid for the family’s meal.',
      },
      {
        word: 'courageous',
        partOfSpeech: 'adjective',
        meaning: 'showing bravery in the face of danger or difficulty.',
        synonyms: ['brave', 'fearless', 'valiant'],
        antonyms: ['cowardly', 'timid'],
        sentence: 'It was courageous of her to dive into the icy river to help.',
      },
      {
        word: 'diligent',
        partOfSpeech: 'adjective',
        meaning: 'showing careful and steady hard work.',
        synonyms: ['hardworking', 'industrious', 'careful'],
        antonyms: ['lazy', 'careless'],
        sentence: 'The diligent student revised every evening before the exam.',
      },
      {
        word: 'fragile',
        partOfSpeech: 'adjective',
        meaning: 'easily broken or damaged.',
        synonyms: ['delicate', 'brittle', 'breakable'],
        antonyms: ['sturdy', 'strong'],
        sentence: 'Please handle the fragile vase with great care.',
      },
      {
        word: 'gigantic',
        partOfSpeech: 'adjective',
        meaning: 'extremely large; enormous.',
        synonyms: ['enormous', 'huge', 'immense'],
        antonyms: ['tiny', 'minuscule'],
        sentence: 'A gigantic wave towered over the small fishing boat.',
      },
      {
        word: 'reluctant',
        partOfSpeech: 'adjective',
        meaning: 'unwilling and hesitant to do something.',
        synonyms: ['unwilling', 'hesitant', 'loath'],
        antonyms: ['eager', 'willing'],
        sentence: 'He was reluctant to leave the warm house on such a cold morning.',
      },
      {
        word: 'vital',
        partOfSpeech: 'adjective',
        meaning: 'absolutely necessary; extremely important.',
        synonyms: ['essential', 'crucial', 'important'],
        antonyms: ['trivial', 'unimportant'],
        sentence: 'Water is vital for the survival of every living thing.',
      },
    ],
  },
  {
    id: 'english-students',
    name: 'Student English',
    short: 'Students',
    audience: 'Students improving their English',
    tagline: 'Academic vocabulary for essays, comprehension, and exams.',
    icon: 'menu_book',
    color: '#7C8C3B',
    comingSoon: true,
    exampleFormat: 'exam',
    words: [
      {
        word: 'analyse',
        partOfSpeech: 'verb',
        meaning: 'to examine something carefully in detail.',
        synonyms: ['examine', 'study', 'evaluate'],
        antonyms: ['ignore', 'overlook'],
        sentence: 'Scientists analyse the data carefully before drawing conclusions.',
      },
      {
        word: 'concise',
        partOfSpeech: 'adjective',
        meaning: 'giving a lot of information clearly in few words.',
        synonyms: ['brief', 'succinct', 'terse'],
        antonyms: ['wordy', 'rambling'],
        sentence: 'Her concise answer made the point in just one sentence.',
      },
      {
        word: 'emphasise',
        partOfSpeech: 'verb',
        meaning: 'to give special importance to something.',
        synonyms: ['stress', 'highlight', 'underline'],
        antonyms: ['downplay', 'understate'],
        sentence: 'The teacher emphasised the importance of reading every day.',
      },
      {
        word: 'inevitable',
        partOfSpeech: 'adjective',
        meaning: 'certain to happen and impossible to avoid.',
        synonyms: ['unavoidable', 'certain', 'sure'],
        antonyms: ['avoidable', 'uncertain'],
        sentence: 'With such heavy rain, flooding seemed inevitable.',
      },
      {
        word: 'justify',
        partOfSpeech: 'verb',
        meaning: 'to show or prove that something is reasonable or right.',
        synonyms: ['defend', 'support', 'warrant'],
        antonyms: ['refute', 'contradict'],
        sentence: 'She could not justify spending so much money on a single toy.',
      },
      {
        word: 'relevant',
        partOfSpeech: 'adjective',
        meaning: 'closely connected to the matter being discussed.',
        synonyms: ['pertinent', 'applicable', 'related'],
        antonyms: ['irrelevant', 'unrelated'],
        sentence: 'Please keep your answer relevant to the question asked.',
      },
      {
        word: 'summarise',
        partOfSpeech: 'verb',
        meaning: 'to give a brief statement of the main points.',
        synonyms: ['condense', 'outline', 'recap'],
        antonyms: ['expand', 'elaborate'],
        sentence: 'Can you summarise the story in three short sentences?',
      },
      {
        word: 'ambiguous',
        partOfSpeech: 'adjective',
        meaning: 'having more than one possible meaning; unclear.',
        synonyms: ['unclear', 'vague', 'equivocal'],
        antonyms: ['clear', 'definite'],
        sentence: 'The ambiguous message left everyone unsure of what to do.',
      },
    ],
  },
  {
    id: 'english-professionals',
    name: 'Everyday English',
    short: 'Everyday',
    audience: 'Adults strengthening their English',
    tagline: 'Advanced, polished vocabulary for confident professional English.',
    icon: 'record_voice_over',
    color: '#8A5A7A',
    comingSoon: true,
    exampleFormat: 'exam',
    words: [
      {
        word: 'mitigate',
        partOfSpeech: 'verb',
        meaning: 'to make something less severe or harmful.',
        synonyms: ['alleviate', 'reduce', 'lessen'],
        antonyms: ['aggravate', 'worsen'],
        sentence: 'The company took steps to mitigate the risks of the new project.',
      },
      {
        word: 'comprehensive',
        partOfSpeech: 'adjective',
        meaning: 'complete and including everything necessary.',
        synonyms: ['thorough', 'complete', 'extensive'],
        antonyms: ['partial', 'incomplete'],
        sentence: 'The report gave a comprehensive overview of the whole market.',
      },
      {
        word: 'feasible',
        partOfSpeech: 'adjective',
        meaning: 'possible to do easily or conveniently.',
        synonyms: ['practicable', 'viable', 'achievable'],
        antonyms: ['impractical', 'impossible'],
        sentence: 'After review, the team agreed the plan was feasible within budget.',
      },
      {
        word: 'concur',
        partOfSpeech: 'verb',
        meaning: 'to agree with someone or something.',
        synonyms: ['agree', 'consent', 'assent'],
        antonyms: ['disagree', 'dissent'],
        sentence: 'I concur with your assessment of the situation.',
      },
      {
        word: 'prudent',
        partOfSpeech: 'adjective',
        meaning: 'acting with care and thought for the future.',
        synonyms: ['sensible', 'cautious', 'wise'],
        antonyms: ['reckless', 'rash'],
        sentence: 'It is prudent to save part of your salary each month.',
      },
      {
        word: 'substantiate',
        partOfSpeech: 'verb',
        meaning: 'to provide evidence that proves something is true.',
        synonyms: ['verify', 'confirm', 'prove'],
        antonyms: ['disprove', 'refute'],
        sentence: 'He could not substantiate his claim with any evidence.',
      },
      {
        word: 'transparent',
        partOfSpeech: 'adjective',
        meaning: 'open and honest, with nothing hidden.',
        synonyms: ['open', 'candid', 'forthright'],
        antonyms: ['secretive', 'opaque'],
        sentence: 'Customers appreciate a company that is transparent about its prices.',
      },
      {
        word: 'diligence',
        partOfSpeech: 'noun',
        meaning: 'careful and persistent effort in your work.',
        synonyms: ['conscientiousness', 'care', 'thoroughness'],
        antonyms: ['negligence', 'carelessness'],
        sentence: 'She completed the audit with great diligence and accuracy.',
      },
    ],
  },
];

export const getTrackById = (id) => TRACKS.find((t) => t.id === id) || null;

export default TRACKS;
